# 1  创建和生成

本节主要介绍 array 的创建和生成。为什么会把这个放在最前面呢？主要有以下两个方面原因：

- 在实际工作过程中，我们时不时需要验证或查看 array 相关的 API 或互操作。
- 有时候在使用 sklearn，matplotlib，PyTorch，Tensorflow 等工具时也需要一些简单的数据进行实验。

所以，先学会如何快速拿到一个 array 是有很多益处的。本节我们主要介绍以下几种常用的创建方式：

- 使用列表或元组
- 使用 arange
- 使用 linspace/logspace
- 使用 ones/zeros
- 使用 random
- 从文件读取

其中，最常用的一般是 linspace/logspace 和 random，前者常常用在画坐标轴上，后者则用于生成「模拟数据」。举例来说，当我们需要画一个函数的图像时，X 往往使用 linspace 生成，然后使用函数公式求得 Y，再 plot；当我们需要构造一些输入（比如 X）或中间输入（比如 Embedding、hidden state）时，random 会异常方便。

## 1.1 从 python 列表或元组创建

重点掌握传入 list 创建一个 array 即可：np.array(list)

需要注意的是：「数据类型」。如果您足够仔细的话，可以发现下面第二组代码第 2 个数字是「小数」（注：Python 中 1. == 1.0），`而array是要保证每个元素类型相同的`，所以会帮您把 array 转为一个 float 的类型。

In [5]:
import numpy as np

In [6]:
## 一个list创建array
l1 = [1,2,3]
a1 = np.array(l1)
print(a1)
print(type(a1))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
## 二维（多维类似）
## 注意，有一个小数哦
a2 = np.array([[1, 2., 3], [4, 5, 6]])
print(a2)
print(type(a2))

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


通过结果发现,numpy会将矩阵中的数字向存在的最高精度进行转换

In [11]:
## 您也可以指定数据类型
a3 = np.array([1, 2, 3], dtype=np.float16)
print(a3)

[1. 2. 3.]


In [16]:
# 如果指定了 dtype，输入的值都会被转为对应的类型，而且不会四舍五入
lst = [
    [1, 2, 3],
    [4, 5, 6.8]
]
np.array(lst, dtype=np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [17]:
# 一个 tuple
np.array((1.1, 2.2))

array([1.1, 2.2])

In [18]:
# tuple，一般用 list 就好，不需要使用 tuple
np.array([(1.1, 2.2, 3.3), (4.4, 5.5, 6.6)])

array([[1.1, 2.2, 3.3],
       [4.4, 5.5, 6.6]])

In [21]:
# 转换而不是上面的创建，其实是类似的，无须过于纠结
np.asarray((1,2,3))

array([1, 2, 3])

In [22]:
np.asarray(([1., 2., 3.], (4., 5., 6.)))

array([[1., 2., 3.],
       [4., 5., 6.]])

## 1.2 使用arange生成

range 是 Python 内置的整数序列生成器，arange 是 numpy 的，效果类似，会生成一维的向量。我们偶尔会需要使用这种方式来构造 array，比如：
- 需要创建一个连续一维向量作为输入（比如编码位置时可以使用）
- 需要观察筛选、抽样的结果时，有序的 array 一般更加容易观察

需要注意的是：在 reshape 时，目标的 shape 需要的元素数量一定要和原始的元素数量相等。


In [1]:
import numpy as np
np.arange(12) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
np.arange(12.0).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
np.arange(100, 124, 2) ## 最后一个参数可以设置步长

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122])

In [4]:
np.arange(100, 124, 2).reshape(3, 2, 2)

array([[[100, 102],
        [104, 106]],

       [[108, 110],
        [112, 114]],

       [[116, 118],
        [120, 122]]])

## 1.3 使用 linspace/logspace 生成

OK，这是我们遇到的第一个比较重要的 API，
- linspace:需要传入 3 个参数：开头，结尾，数量；
- logspace:后者需要额外传入一个 base，它默认是 10。

In [6]:
np.linspace(0,100,10) ## 这是一个线性增长的过程

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [8]:
np.linspace(0,9,6)

array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

In [19]:
np.logspace(0, 9, 6,base = np.e)

array([1.00000000e+00, 6.04964746e+00, 3.65982344e+01, 2.21406416e+02,
       1.33943076e+03, 8.10308393e+03])

In [20]:
np.log(_)

array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

In [22]:
import matplotlib as plt

N = 20
x = np.arange(N)
y1 = np.linspace(0, 10, N) * 100
y2 = np.logspace(0, 10, N, base=2)

plt.plot(x, y2, '*');
plt.plot(x, y1, 'o');


AttributeError: module 'matplotlib' has no attribute 'plot'

## 1.4 使用 ones/zeros 创建

创建全 1/0 array 的快捷方式。需要注意的是 np.zeros_like 或 np.ones_like，二者可以快速生成给定 array 一样 shape 的 0 或 1 向量，这在需要 Mask 某些位置时可能会用到。

In [25]:
np.ones((3))

array([1., 1., 1.])

In [26]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
## 像给定向量那样的 0 向量（ones_like 是 1 向量）
np.zeros_like(np.ones((2,3,3)))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## 1.5 使用random生成

如果要在这一节选一个最重要的 API，那一定是 random 无疑了，这里我们只介绍几个比较常用的「生产」数据相关的 API。它们经常用于随机生成训练或测试数据，神经网路初始化等。


需要注意的是：这里我们统一推荐使用新的 API 方式创建，即通过 np.random.default_rng() 先生成 Generator，然后再在此基础上生成各种分布的数据（记忆更加简便清晰）。不过我们依然会介绍旧的 API 用法，因为很多代码中使用的还是旧的，您可以混个眼熟。

In [30]:
## 0-1 连续均匀分布
np.random.rand(2, 3)

array([[0.17333751, 0.20795057, 0.11376537],
       [0.80214716, 0.39539857, 0.8380014 ]])

In [33]:
## 单个数
np.random.rand()

0.11133776399374562

In [34]:
## 0-1 连续均匀分布
np.random.random((3, 2))

array([[0.4762032 , 0.65429106],
       [0.46551767, 0.43771629],
       [0.79512353, 0.58162703]])

In [35]:
# 指定上下界的连续均匀分布
np.random.uniform(-1, 1, (2, 3))

array([[ 0.29896603, -0.00835357,  0.72067645],
       [-0.66538797, -0.89421292, -0.42289647]])

In [36]:
# 上面两个的区别是 shape 的输入方式不同，无伤大雅了
# 不过从 1.17 版本后推荐这样使用（以后大家可以用新的方法）
# rng 是个 Generator，可用于生成各种分布
rng = np.random.default_rng(42)
rng

Generator(PCG64) at 0x7FDB61C744A0

In [39]:
# 推荐的连续均匀分布用法
rng.random((2, 3))

array([[0.64386512, 0.82276161, 0.4434142 ],
       [0.22723872, 0.55458479, 0.06381726]])

In [40]:
# 可以指定上下界，所以更加推荐这种用法
rng.uniform(-1, 1, (2, 3))

array([[ 0.65526234,  0.2633288 ,  0.51617548],
       [-0.29094806,  0.94139605,  0.78624224]])

In [42]:
np.random.randint(0,10,(2,3))

array([[3, 3, 4],
       [9, 2, 6]])

In [46]:
# 上面推荐的方法，指定大小和上界
rng.integers(8,10, size=2)

array([8, 8])

#### 标准正太分布(均值为0，方差为1)

In [57]:
np.random.randn(2,4) #旧的标准正太分布用法

TypeError: 'tuple' object cannot be interpreted as an integer

In [48]:
rng.standard_normal((2,4)) # 推荐的新的标准正态分布用法

array([[ 0.41273261,  0.430821  ,  2.1416476 , -0.40641502],
       [-0.51224273, -0.81377273,  0.61597942,  1.12897229]])

#### 高斯分布

In [51]:
# 高斯分布
np.random.normal(0, 1, (3, 5))

array([[-0.24825718, -0.85640089,  0.86610248,  0.33282606, -0.57858101],
       [ 0.30110469,  0.10975573, -0.86569706, -0.62337304, -1.11561317],
       [-0.68379758, -1.58170912, -0.11245201,  0.14009065,  0.2750349 ]])

In [52]:
# 上面推荐的高斯分布用法
rng.normal(0, 1, (3, 5))

array([[-0.11394746, -0.84015648, -0.82448122,  0.65059279,  0.74325417],
       [ 0.54315427, -0.66550971,  0.23216132,  0.11668581,  0.2186886 ],
       [ 0.87142878,  0.22359555,  0.67891356,  0.06757907,  0.2891194 ]])

总之，一般会用的就是2个分布：均匀分布和正态（高斯）分布。另外，size 可以指定 shape。

In [53]:
rng = np.random.default_rng(42)

In [54]:
# 离散均匀分布
rng.integers(low=0, high=10, size=5)

array([0, 7, 6, 4, 4])

In [55]:
# 连续均匀分布
rng.uniform(low=0, high=10, size=5)

array([6.97368029, 0.94177348, 9.75622352, 7.61139702, 7.86064305])

In [56]:
# 正态（高斯）分布
rng.normal(loc=0.0, scale=1.0, size=(2, 3))

array([[-0.01680116, -0.85304393,  0.87939797],
       [ 0.77779194,  0.0660307 ,  1.12724121]])

## 1.6 从文件读取

主要用于加载实现存储好的权重参数或预处理好的数据集，有时候会比较方便，比如训练好的模型参数加载到内存里用来提供推理服务，或者耗时很久的预处理数据直接存起来，多次实验时不需要重新处理。

需要注意的是：存储时不需要写文件名后缀，会自动添加。

#### 保存array操作:save、savez、savez_compressed

In [63]:
## 直接将给定矩阵存为 a.npy(在磁盘上)
np.save('./a', np.array([[1, 2, 3], [4, 5, 6]]))

In [64]:
## 可以将多个矩阵存在一起，名为 `b.npz`
np.savez("./b", a=np.arange(12).reshape(3, 4), b=np.arange(12.).reshape(4, 3))

In [65]:
## 和上一个一样，只是压缩了
np.savez_compressed("./c", a=np.arange(12).reshape(3, 4), b=np.arange(12.).reshape(4,3))

#### 接着上面的保存操作,进行读取

In [67]:
a = np.load("./a.npy")
print(a)

[[1 2 3]
 [4 5 6]]


In [69]:
# 加载多个，可以像字典那样取出对应的 array
arr = np.load("./b.npz")
print(arr["a"])
print(arr["b"])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [70]:
# 后缀都一样，你干脆当它和上面的没区别即可
arr = np.load("./c.npz")
print(arr["a"])
print(arr["b"])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
