# 分解与组合

这节我们主要学习 array 的分解和组合，本节是所有章节中最重要的一节，通过本节内容，您可以充分了解 numpy（以及 Python 语言）的强大，这种操作上的优雅不能说后无来者，但至少前无古人了。

内容大致包括以下小节：

- 切片和索引
- 拼接
- 重复
- 分拆

其中，重中之重是「切片和索引」，它基础、它高频、它无处不在。我们强烈建议您熟练掌握，其他三个相对简单，只需要各记住一个 API 即可

## 4.1 切片和索引

划重点！切片和索引是通过对已有 array 进行操作而得到想要的「部分」元素的行为过程。其核心动作可以概括为：按维度根据 start:stop:step 操作 array。


这部分内容的核心是把处理按维度分开，不处理的维度统一用 : 或 ... 代替；在看操作时，也要首先关注「,」在哪里。要处理的维度和之前 arange linspace 等接口使用方法是一样的。

⚠️ 需要注意的是：引支持负数，即从后往前索引。

In [1]:
import numpy as np

rng = np.random.default_rng(42)
arr = rng.integers(0,20,(5,4))

print(arr)

[[ 1 15 13  8]
 [ 8 17  1 13]
 [ 4  1 10 19]
 [14 15 14 15]
 [10  2 16  9]]


`index/slice`

In [3]:
# 取第0行
print(arr[0])
# 取第3行
print(arr[3])



[ 1 15 13  8]
[14 15 14 15]


In [4]:
# 取第0行的第1个元素
print(arr[0,1])

15


In [5]:
# 然后带点连续的范围 第0~2行
print(arr[0:3])

[[ 1 15 13  8]
 [ 8 17  1 13]
 [ 4  1 10 19]]


In [6]:
# 离散也可以:第0,3行
print(arr[[0,3]])

[[ 1 15 13  8]
 [14 15 14 15]]


In [9]:
# 再来加上维度,取第1~2行的第1列
print(arr[1:3,1])

[17  1]


In [10]:
# 离散也是一样的,第1,3行，第0列
arr[[1,3],[0]]

array([ 8, 14])